//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPERP2015.MP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string ContentUrl { get; set; }
        public int ParentId { get; set; }
        public string CssClass { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
